-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : sam. 30 nov. 2024 à 19:38
-- Version du serveur : 10.4.32-MariaDB
-- Version de PHP : 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `sri_films`
--

-- --------------------------------------------------------

--
-- Structure de la table `movie`
--

CREATE TABLE `movie` (
  `file_name` varchar(255) NOT NULL,
  `cast` varchar(255) DEFAULT NULL,
  `genres` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `video` varchar(255) DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  `extract` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `movie`
--

INSERT INTO `movie` (`file_name`, `cast`, `genres`, `title`, `video`, `year`, `extract`) VALUES
('All_My_Life.pdf', ' Jessica Rothe, Harry Shum Jr., Kyle Allen, Chrissie Fit, Jay Pharoah, Marielle Scott , Keala Settle', ' Drama, Romance', 'All My Life', 'https://www.youtube.com/watch?v=mWyJvohEFj8', 2020, ' All My Life is a 2020 American romantic drama film directed by Marc Meyers, from a screenplay\r\n by Todd Rosenberg, based on the true story of Solomon Chau and Jennifer Carter, a young\r\n couple that rushes to put their wedding together after Solomon is di'),
('An_American_Pickle.pdf', 'Seth Rogen, Sarah Snook', 'Comedy, Drama', 'An American Pickle', 'https://youtu.be/ipL_67qHzCw?si=PJlNCD9KcALGFV_o', 2020, 'An American Pickle is a 2020 American comedy-drama film directed \r\nby Brandon Trost and written by Simon Rich, based on his 2013 short story \r\n\\\"Sell Out\\\". The film stars Seth Rogen as an Eastern European Jewish \r\nimmigrant who gets preserved in a vat of'),
('A_Fall_from_Grace.pdf', 'Crystal R. Fox, Phylicia Rashad , Bresha Webb , Mehcad Brooks , Cicely Tyson, Tyler Perry', 'Thriller', 'A Fall from Grace', 'https://youtu.be/FjtXfL_vfzU?si=QMlFhoPczgAMaxSB', 2020, 'A Fall from Grace is a 2020 American thriller film produced, written, \r\nand directed by Tyler Perry and his first to be released by Netflix. The film \r\nfollows a woman who finds a dangerous new love and the novice attorney \r\nwho defends her in a sensation'),
('Bad_Boys_for_Life.pdf', 'Will Smith, Martin Lawrence, Vanessa Hudgens, Alexander Ludwig, Charles Melton, Paola Núñez, Kate del Castillo, Nicky Jam,Joe Pantoliano,', 'Action , Comedy', 'Bad Boys for Life', 'https://youtu.be/1_Ot2eTcoU8?si=S_njr4tvDtsooRoX', 2020, 'Bad Boys for Life is a 2020 American buddy cop action comedy \r\nfilm directed by Adil & Bilall. It is the sequel to Bad Boys II 2003 and the \r\nthird installment in the Bad Boys franchise. Will Smith, Martin Lawrence, \r\nJoe Pantoliano, and Theresa Randle '),
('Black_Bear.pdf', 'Aubrey Plaza, Christopher Abbott, Sarah Gadon', 'Comedy, Drama, Thriller', 'Black Bear', 'https://www.youtube.com/watch?v=1_gCDYMGnng', 2020, ' Black Bear is a 2020 American black comedy-drama thriller film written and directed by\r\n Lawrence Michael Levine. It stars Aubrey Plaza, Christopher Abbott, Sarah Gadon, Paola\r\n Lázaro and Grantham Coleman.'),
('Black_Beauty.pdf', 'Mackenzie Foy, Kate Winslet, Claire Forlani, Fern Deacon, Iain Glen', 'Adventure, Drama, Family', 'Black Beauty', 'https://www.youtube.com/watch?v=wpZqSJSR5PY', 2020, ' Black Beauty is a 2020 adventure drama family film written, edited and directed by Ashley Avis\r\n and based on the 1877 novel of the same name by Anna Sewell. A co-production between the\r\n United States, the United Kingdom, South Africa, France and German'),
('Black_Is_King.pdf', 'Beyoncé', 'Musical', 'Black Is King', 'https://youtu.be/vKC1eJ-bGvw?si=IUbxXyRU25P5AR7E', 2020, ' Black Is King is a 2020 American musical film and visual album \r\ndirected, written, and executive produced by American singer Beyoncé. It is a \r\nvisual companion to the 2019 album The Lion King: The Gift, curated by \r\nBeyoncé for The Lion King 2019. It'),
('Buddy_Games.pdf', 'Josh Duhamel, Dax Shepard, Olivia Munn', 'Comedy', 'Buddy Games', 'https://www.youtube.com/watch?v=jDW2AUrTq-E', 2020, ' Buddy Games is a 2019 American comedy film directed by Josh Duhamel in his solo directorial\r\n debut and written by Duhamel, Bob Schwartz, and Jude Weng. Produced by Duhamel, Michael\r\n J. Luisi, and Weng, the film centers on a group of six friends that re'),
('Deep_Blue_Sea_3.pdf', 'Tania Raymonde, Nathaniel Buzolic, Emerson Brooks, Bren Foster', 'horror, Science Fiction', 'Deep Blue Sea 3', 'https://youtu.be/_z65kOeS1HE?si=gKyj3-i_8vO2BoE0', 2020, ' Deep Blue Sea 3 is a 2020 American science fiction natural horror film, \r\nstarring Tania Raymonde. Dr. Emma Collins and her team are on Little Happy \r\nIsland studying the effect of climate change on great white sharks who come to \r\nthe nearby nursery eve'),
('Dolittle.pdf', ' Robert Downey Jr , Antonio Banderas\r\n , Michael Sheen, Emma Thompson\r\n ,Rami Malek ,John Cena ,Kumail Nanjiani, Octavia Spencer,Tom Holland\r\n ,Craig Robinson ,Ralph Fiennes ,Selena Gomez ,Marion Cotillard', 'Adventure , Fantasy', 'Dolittle', 'https://youtu.be/QCP88nLAtn4?si=MDizsiNt6B02Kzm9', 2020, 'Dolittle is a 2020 American fantasy adventure film directed by \r\nStephen Gaghan from a screenplay by Gaghan, Dan Gregor, and Doug \r\nMand, based on a story by Thomas Shepherd. Dolittle is based on the title \r\ncharacter created by Hugh Lofting and is primar'),
('Folklore__The_Long_Pond_Studio_Sessions.pdf', 'Taylor Swift, Jack Antonoff, Aaron Dessner, Justin Vernon', 'Documentary, Performance', 'Folklore: The Long Pond Studio Sessions', 'https://www.youtube.com/watch?v=K-a8s8OLBSE', 2020, ' Folklore: The Long Pond Studio Sessions is a 2020 American documentary concert film\r\n directed and produced by American singer-songwriter Taylor Swift, released on Disney+ on\r\n November 25, 2020. The documentary is set at Long Pond Studio, an isolated re'),
('Godmothered.pdf', 'Isla Fisher, Jillian Bell, Santiago Cabrera', 'Comedy, Drama, Fantasy', 'Godmothered', 'https://www.youtube.com/watch?v=5m6u022D3RU', 2020, ' Godmothered is a 2020 American fantasy comedy-drama film directed by Sharon Maguire,\r\n written by Kari Granlund and Melissa Stack, and starring Jillian Bell and Isla Fisher. The Walt\r\n Disney Company first began developing the film in September 2019, wit'),
('Gretel__Hansel.pdf', ' Sophia Lillis , Sammy Leakey ,Charles Babalola , Jessica De Gouw , Alice Krige', ' Fantasy , Horror', 'Gretel & Hansel', 'https://youtu.be/AEE4fNVYBQk?si=9qgfx7cADHy8c18v', 2020, ':Gretel & Hansel is a 2020 dark fantasy horror film based on the \r\nGerman folklore tale Hansel and Gretel by the Brothers Grimm. Directed by \r\nOz Perkins and produced by Fred Berger, Brian Kavanaugh-Jones, and Dan \r\nKagan, with a screenplay by Rob Hayes. '),
('Half_Brothers.pdf', 'Luis Gerardo Méndez, Connor Del Rio', 'Comedy', 'Half Brothers', 'https://www.youtube.com/watch?v=tmxxfuLPWXg', 2020, 'Half Brothers is a 2020 American comedy film directed by Luke Greenfield from a screenplay by\r\n Eduardo Cisneros and Jason Shuman. It stars Luis Gerardo Méndez, Connor Del Rio, José\r\n Zúñiga, Vincent Spano, Pia Watson and Juan Pablo Espinosa'),
('Happiest_Season.pdf', 'Kristen Stewart, Mackenzie Davis, Alison Brie, Aubrey Plaza, Dan Levy, Mary Holland, Victor Garber, Mary Steenburgen', 'Comedy, Drama, Romance', 'Happiest Season', 'https://www.youtube.com/watch?v=h58HkQV1gHY', 2020, ' Happiest Season is a 2020 American holiday romantic comedy-drama film directed by Clea\r\n DuVall, who co-wrote the screenplay with Mary Holland. Starring an ensemble cast consisting\r\n of Kristen Stewart, Mackenzie Davis, Alison Brie, Aubrey Plaza, Dan Lev'),
('Jiu_Jitsu.pdf', 'Alain Moussi, Frank Grillo, JuJu Chan, Tony Jaa, Nicolas Cage', 'Martial Arts, Science Fiction', 'Jiu Jitsu', 'https://www.youtube.com/watch?v=B4Nz8WFYNHA', 2020, ' Jiu Jitsu is a 2020 American science fiction martial arts film directed and co-written by Dimitri\r\n Logothetis and starring Alain Moussi, Frank Grillo, JuJu Chan, Tony Jaa and Nicolas Cage. The\r\n film is based on the 2017 comic book of the same name by L'),
('Let_Them_All_Talk.pdf', 'Meryl Streep, Candice Bergen, Gemma Chan, Lucas Hedges, Dianne Wiest', 'Comedy, Drama', 'Let Them All Talk', 'https://www.youtube.com/watch?v=Ljf8DOZBnoA', 2020, ' Let Them All Talk is a 2020 American comedy-drama film directed by Steven Soderbergh from\r\n a screenplay by Deborah Eisenberg. The film stars Meryl Streep, Dianne Wiest, Candice\r\n Bergen, Lucas Hedges, and Gemma Chan. Much of the dialogue was improvised '),
('Life_in_a_Year.pdf', 'Jaden Smith, Cara Delevingne, Cuba Gooding Jr., Nia Long', 'Drama, Romance', 'Life in a Year', 'https://www.youtube.com/watch?v=BgmJ14p4Uuk', 2020, ' Life in a Year is a 2020 American romantic drama film directed by Mitja Okorn, from a\r\n screenplay by Jeffrey Addiss and Will Matthews. The film stars Jaden Smith, Cara Delevingne,\r\n Cuba Gooding Jr., and Nia Long. Will Smith and Jada Pinkett Smith serve'),
('Like_a_Boss.pdf', 'Tiffany Haddish, Rose Byrne ,Salma Hayek\r\n , Jennifer Coolidge , Billy Porter', 'Comedy', 'Like a Boss', 'https://youtu.be/UEJLN8cEdEw?si=mPj7CjpjppXqMQK1', 2020, ':Like a Boss is a 2020 American comedy film directed by Miguel \r\nArteta, written by Sam Pitman and Adam Cole-Kelly, and starring Tiffany \r\nHaddish, Rose Byrne, and Salma Hayek. The plot follows two friends who \r\nattempt to take back control of their cosme'),
('Magic_Camp.pdf', 'Adam DeVine, Gillian Jacobs, Jeffrey Tambor', 'Comedy, Family, Fantasy', 'Magic Camp', 'https://youtu.be/vEHzdlwjlU4?si=gOwFDYqI_Y_ivI4K', 2020, 'Magic Camp is a 2020 American fantasy comedy family film directed \r\nby Mark Waters. Micah Fitzerman-Blue, Noah Harpster, Matt Spicer, Max \r\nWinkler, Dan Gregor and Doug Mand serve as co-screenwriters, with an \r\noriginal story written by Gabe Sachs, Jeff J'),
('Ma_Rainey_s_Black_Bottom.pdf', ' Viola Davis, Chadwick Boseman, Glynn Turman, Colman Domingo, Michael Potts,\r\n Jeremy Shamos, Taylour Paige, Dusan Brown, Jonny Coyne', 'Drama', 'Ma Rainey\'s Black Bottom', 'https://www.youtube.com/watch?v=ord7gP151vk', 2020, ' Ma Rainey\'s Black Bottom is a 2020 American drama film directed by George C. Wolfe and\r\n written by Ruben Santiago-Hudson, based on the 1982 play of the same name by August\r\n Wilson. The film stars Viola Davis, Chadwick Boseman, Glynn Turman, Colman Domi'),
('Money_Plane.pdf', ' Adam Copeland ,\r\n Kelsey Grammer ,\r\n Thomas Jane ,\r\n Denise Richards ,\r\n Katrina Norman ,\r\n Patrick Lamont Jr ,\r\n Andrew Lawrence ,\r\n Joey Lawrence ,\r\n Matthew Lawrence', 'Action', 'Money Plane', 'https://youtu.be/Hww1sF90VmY?si=DuHQTucIZyafIvIr', 2019, 'Money Plane is a 2019 American action film directed by Andrew \r\nLawrence and starring Adam Copeland, Kelsey Grammer, Thomas Jane, \r\nand Denise Richards. It was released to video-on-demand services on July \r\n10, 2020, by Quiver Distribution.'),
('Project_Power.pdf', 'Jamie Foxx, Joseph Gordon-Levitt, Dominique Fishback, Rodrigo \r\nSantoro, Machine Gun Kelly, Allen Maldonado, Amy Landecker, Courtney B. \r\nVance, C.J. LeBlanc', 'Action, Science Fiction', 'Project Power', 'https://youtu.be/oTm4sEfA5vI?si=4S6FsT7QqJflaF1S', 2019, ' Project Power is a 2020 American science fiction action film directed \r\nby Henry Joost and Ariel Schulman, produced by Eric Newman and Bryan \r\nUnkeless, and written by Mattson Tomlin. It stars Jamie Foxx, Joseph Gordon\r\nLevitt, and Dominique Fishback, a'),
('Red_Notice.pdf', 'Dwayne Johnson, Ryan Reynolds, Gal Gadot, Chris Diamantopoulos, Ritu Arya', 'Action, Comedy', 'Red Notice', 'https://www.youtube.com/watch?v=Pj0wz7zu3Ms', 2021, ' Red Notice is a 2021 American action comedy film written and directed by Rawson Marshall\r\n Thurber starring Dwayne Johnson alongside Ryan Reynolds and Gal Gadot and Ritu Arya. It\r\n marks the third collaboration between Thurber and Johnson, following Cent'),
('She_Dies_Tomorrow.pdf', 'Kate Lyn Sheil, Jane Adams, Kentucker Audley, Katie Aselton, Adam \r\nWingard', 'Thriller', 'She Dies Tomorrow', 'https://www.youtube.com/watch?si=9AorTKPQCMy7RQn-&v=MmqGW4wkSGU&feature=youtu.be', 2020, 'She Dies Tomorrow is a 2020 American psychological thriller film \r\nwritten, directed, and produced by Amy Seimetz. It stars Kate Lyn Sheil, Jane \r\nAdams, Kentucker Audley, Katie Aselton, Chris Messina, Tunde Adebimpe, \r\nJennifer Kim, Olivia Taylor Dudley,'),
('Summerland.pdf', 'Gemma Arterton, Gugu Mbatha-Raw, Penelope Wilton, Tom Courtenay', 'Drama', 'Summerland', 'https://youtu.be/Yi58keaYSkE?si=iMOTuKjEBvf-HKR', 2020, ' Summerland is a 2020 British drama film written and directed by \r\nJessica Swale, starring Gemma Arterton, Gugu Mbatha-Raw, Lucas Bond, Dixie \r\nEgerickx, Siân Phillips, Penelope Wilton and Tom Courtenay.'),
('Superintelligence.pdf', 'Melissa McCarthy, Bobby Cannavale, Brian Tyree Henry, Jean Smart, James Corden', 'Action, Comedy, Romance', 'Superintelligence', 'https://www.youtube.com/watch?v=ghgafY27kUM', 2020, 'Superintelligence is a 2020 American romantic action comedy film directed by Ben Falcone and\r\n written by Steve Mallory. The film stars Melissa McCarthy in her fourth collaboration with her\r\n husband, Falcone.'),
('The_Christmas_Chronicles_2.pdf', 'Kurt Russell, Goldie Hawn, Darby Camp, Julian Dennison, Jazhir Bruno, Judah Lewis, Kimberly Williams-Paisley, Tyrese Gibson, Andrew Morgado', 'Comedy', 'The Christmas Chronicles 2', 'https://www.youtube.com/watch?v=HVzBwSOcBaI', 2020, ' The Christmas Chronicles 2 is a 2020 American Christmas comedy film directed and produced\r\n by Chris Columbus, who wrote the screenplay with Matt Lieberman. A sequel to the 2018 film\r\n The Christmas Chronicles, it features Kurt Russell reprising his role'),
('The_Croods__A_New_Age.pdf', ' Nicolas Cage, Emma Stone, Ryan Reynolds, Peter Dinklage, Leslie Mann, Kelly Marie Tran, Catherine Keener, Clark Duke, Cloris Leachman', 'Adventure, Animated, Comedy', 'The Croods: A New Age', 'https://www.youtube.com/watch?v=GkXeVIfbJOw', 2020, ' The Croods: A New Age is a 2020 American computer-animated adventure comedy film\r\n produced by DreamWorks Animation and distributed by Universal Pictures. The sequel to The\r\n Croods (2013) as well as the second film in The Croods franchise, it was direct'),
('The_Gentlemen.pdf', ' Matthew McConaughey , Charlie Hunnam ,\r\n Henry Golding , Michelle Dockery ,\r\n Jeremy Strong , Eddie Marsan ,\r\n Colin Farrell , Hugh Grant', ' Action , Comedy', 'The Gentlemen', 'https://youtu.be/kbnLvKkoT24?si=GFu3WklCqLuUXalR', 2020, ''),
('The_Grudge.pdf', ' Andrea Riseborough , Demián Bichir ,\r\n John Cho , Betty Gilpin , Lin Shaye ,\r\n Jacki Weaver', 'Horror , Supernatural', 'The Grudge', 'https://youtu.be/gMSq0aX2MSY?si=UMMe-ebSL6chOHa_', 2020, 'The Grudge is a 2020 American psychological supernatural horror \r\nfilm written and directed by Nicolas Pesce. Originally announced as a \r\nreboot of the 2004 American remake and the original 2002 Japanese \r\nhorror film Ju-On: The Grudge, the film ended up '),
('The_Last_Vermeer.pdf', 'Guy Pearce, Claes Bang, Vicky Krieps', 'Drama', 'The Last Vermeer', 'https://www.youtube.com/watch?v=Ftc3XXd_1tk', 2020, ' The Last Vermeer is a 2019 American drama film directed by Dan Friedkin from a screenplay\r\n by John Orloff, Mark Fergus, and Hawk Ostby. It is based on the 2008 book The Man Who\r\n Made Vermeers by Jonathan Lopez, and tells the story of Han van Meegeren, '),
('The_Midnight_Sky.pdf', 'George Clooney, Felicity Jones, David Oyelowo, Tiffany Boone, Demián Bichir, Kyle\r\n Chandler, Caoilinn Springall', 'Science Fiction', 'The Midnight Sky', 'https://www.youtube.com/watch?v=DXUUqr3AFKs&t=4s', 2020, ' The Midnight Sky is a 2020 American science fiction film directed by George Clooney based on\r\n the 2016 novel Good Morning, Midnight by Lily Brooks-Dalton. The script was written by Mark\r\n L. Smith. Clooney plays a leading role in his film, as an aging s'),
('The_Rhythm_Section.pdf', ' Blake Lively ,\r\n Jude Law ,\r\n Sterling K. Brown', ' Action , Thriller', 'The Rhythm Section', 'https://youtu.be/pfwr-g8lUFs?si=8PVr78MYQEFGgX0', 2020, 'The Rhythm Section is a 2020 action thriller film directed by Reed \r\nMorano, with a screenplay by Mark Burnell based on his novel of the same \r\nname. Starring Blake Lively, Jude Law, and Sterling K. Brown, it follows a \r\ngrieving woman who seeks revenge a'),
('The_Secret_Dare_To_Dream.pdf', ' Katie Holmes, Josh Lucas, Jerry O\'Connell, Celia Weston', 'Drama', 'The Secret: Dare To Dream', 'https://youtu.be/DnRP4uaThcE?si=R22GVKpqWLtrO3YE', 2020, 'The Secret: Dare to Dream is a 2020 American drama film based on the 2006 \r\nself-help book The Secret by Rhonda Byrne. Directed by Andy Tennant, from a \r\nscreenplay he wrote with Bekah Brunstetter and Rick Parks, it stars Katie Holmes, Josh \r\nLucas, Jerry'),
('The_Tax_Collector.pdf', ' Bobby Soto, Shia LaBeouf, Cinthya Carmona, George Lopez', 'Action, Thriller', 'The Tax Collector', 'https://youtu.be/Cr9aBJMwRVM?si=SA3moeUuu10_uF24', 2020, 'The Tax Collector is a 2020 American action thriller film written, \r\ndirected, and produced by David Ayer. The film stars Bobby Soto, Cinthya \r\nCarmona, George Lopez, and Shia LaBeouf, and follows two enforcers working \r\nfor a Los Angeles crime lord whose'),
('Three_Christs.pdf', ' Richard Gere ,\r\n Peter Dinklage ,\r\n Walton Goggins ,\r\n Bradley Whitford', 'Drama', 'Three Christs', 'https://youtu.be/09zYzvKkCOA?si=ML6nlXsMM3JRNPuy', 2020, 'Three Christs, also known as State of Mind, is a 2017 American \r\ndrama film directed, co-produced, and co-written by Jon Avnet and based \r\non Milton Rokeach\'s nonfiction book The Three Christs of Ypsilanti. It \r\nscreened in the Gala Presentations section '),
('Uncle_Frank.pdf', 'Paul Bettany, Sophia Lillis, Peter Macdissi, Judy Greer, Steve Zahn, Lois Smith, Margo\r\n Martindale, Stephen Roo', 'Comedy, Drama', 'Uncle Frank', 'https://www.youtube.com/watch?v=QsNgR-dguhQ', 2020, ' Uncle Frank is a 2020 American comedy-drama film written, directed, and co-produced by Alan\r\n Ball. The film stars Paul Bettany and Sophia Lillis. Set in the 1970s, Uncle Frank is a road\r\n movie about a gay man who confronts his past'),
('Underwater.pd', ' Kristen Stewart ,\r\n Vincent Cassel ,\r\n Jessica Henwick ,\r\n John Gallagher Jr,\r\n Mamoudou Athie ,\r\n T.J. Miller', 'Action ,Horror ,Science Fiction', 'Underwater', 'https://youtu.be/9G2Y12jZXgk?si=y7DY3_N2P3isrC3Y', 2020, ':Underwater is a 2020 American science fiction action horror film \r\ndirected by William Eubank. The film stars Kristen Stewart, Vincent Cassel, \r\nJessica Henwick, John Gallagher Jr., Mamoudou Athie, and T.J. Miller'),
('Waiting_for_the_Barbarians.pdf', 'Mark Rylance, Johnny Depp, Robert Pattinson, Gana Bayarsaikhan, Greta  Scacchi', 'Drama', 'Waiting for the Barbarians', 'https://www.youtube.com/watch?si=pOdVwQAJWH3evesP&v=7p7Wb25yZDU&feature=youtu.be', 2020, 'Waiting for the Barbarians is a 2019 drama film directed by Ciro Guerra in his  English-language directorial debut. The film is based on the 1980 novel of the same  name by J. M. Coetzee. It stars Mark Rylance, Johnny Depp, Robert Pattinson, Gana  Bayarsa'),
('Wander.pdf', 'Aaron Eckhart, Katheryn Winnick, Heather Graham, Roger Dorman, Tommy Lee Jones', 'Thriller', 'Wander', 'https://youtube.com/watch?v=ioWdag5IhFk', 2021, ' Wander is a 2021 American thriller film directed by April Mullen and written by Tim Doiron. It\r\n stars Tommy Lee Jones, Aaron Eckhart, Katheryn Winnick, Heather Graham, and Roger\r\n Dorman. The story focuses on two conspiracy theorists and their investiga');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `movie`
--
ALTER TABLE `movie`
  ADD PRIMARY KEY (`file_name`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
